### ISSUE TITLE
readme里的电子书下载地址403了

### ISSUE THREAD

**Issue by mumu1993** [semlinker/awesome-typescript#88]

**Comment by semlinker** [comment]
全栈修仙之路-重学TS
链接: https://pan.baidu.com/s/1E8vbrLYSla9sraDKehrDJg 提取码: 44tw

**Comment by semlinker** [comment]
1、全栈修仙之路-重学TS
链接: https://pan.baidu.com/s/1E8vbrLYSla9sraDKehrDJg 提取码: 44tw
2、全栈修仙之路-源码探秘篇
链接: https://pan.baidu.com/s/1xUV2yV9W1GwTCzgLABRB3A 提取码: cq49
3、全栈修仙之路-前端进阶篇
链接: https://pan.baidu.com/s/1XEiLggdZ13vkerVX75FpTA 提取码: 7mta

**Comment by semlinker** [comment]
README 电子书下载地址已更新。
