### ISSUE TITLE
疑惑返回类型加Partial为什么不行

### ISSUE THREAD

**Issue by zhanghan3** [semlinker/awesome-typescript#89]
type User = {
  id: number
  kind: string
}

// 这样会报错
function makeCustomer<T extends User>(u: T): Partial<T> {
  return { id: 1, kind: '' }
}

// 看了大家回答的原因是由于 T 类型只是继承了User类型，所以可能会有除了id、kind之外的类型，所以只返回带id、kind的类型是不对的。
// 但是我给返回类型加了Partial，按理说返回类型的属性是可选的，即便只有id、number也可以满足要求。但是为什么还报错呢。
// PS: 返回值给 {} 一个空对象不报错

**Comment by semlinker** [comment]
Type '{ id: number; kind: string; }' is not assignable to type 'Partial<T>'，T 是泛型变量， `{ id: 1, kind: '' }` 已经限定了对象的类型。
